### ISSUE TITLE
Userstory: Accessibility des Frontends verbessern

### ISSUE THREAD

**Issue by christopherpross** [Bootstrap-Academy/Bootstrap-Academy#74]
Username Academy: cpross
Kontakt: cpross@cpross:matrix.org

Hallo zusammen,

ich bin ein sehbehinderter Nutzer der Academy und kenne zwei weitere Nutzer, die eine Sehbehinderung haben.
Deshalb habe ich mich entschlossen, mit euch zusammen die Barrierefreiheit (Accessibility) der Academy zu verbessern.

Ich möchte versuchen, viele der Probleme selbst zu lösen, aber leider kann ich einige Probleme nicht selbst lösen. Da ich auch nur begrenzt Zeit habe und manche Probleme auch besser von einem sehenden Benutzer verbessert werden sollten.

Dieses Ticket soll einen Überblick geben, welche Probleme gelöst werden müssen. Ich bin natürlich für Feedback offen, falls es mit diesem Ticket Probleme gibt oder weitere Fragen bestehen, könnt ihr mich gern kontaktieren.

Ich werde versuchen, die To-do-Liste im Laufe der Zeit zu aktualisieren, je nachdem, was mir auffällt oder welche neuen Aufgaben hinzukommen.

Lasst uns die Academy zu einer Website machen, die jeder nutzen kann, auch Menschen mit Behinderungen.

Aufgaben:

- [x] Bildbeschreibungen verwenden (alttext): #82
- [ ] Möglichkeit, Schriftgröße, Hintergrundfarbe und Textfarbe anzupassen. Evtl. mit Themes: Tracked in #143 
- [ ] ARIA-Roles & Properties ~Tracked in #144
- [ ] Transcripts & Captions for the videos - to be done in the future (we need to download the videos first #142  )

**Comment by TheMorpheus407** [comment]
This is a very long task and I appreciate everyone committing some effort into it. I estimated a rough bounty for it, but everyone who commits code for these tasks will get some portion of it.

**Comment by christopherpross** [comment]
@TheMorpheus407 
Should I create an issue for each task? I am currently working on the image descriptions.

**Comment by TheMorpheus407** [comment]
It might be helpful to do so, yes. We can mark this as epic then. Thanks!

**Comment by TheMorpheus407** [comment]
Created Issues on each matter and updated the first post to match the issues.
I probably need feedback here from people who know about it, so when each issue is done, we will need to continue improving everything

**Comment by TheMorpheus407** [comment]
Will take care of this and full accessibility when we made it through the required changes with the academy
